### PR TITLE
Add to the job lists

### PR DESCRIPTION
**Pull request by FLYSTEPHEN**
Add job list from Linkedin and Glassdoor. The Linkedin's list need to be tested later.

### CODE REVIEW

**Comment by hupili** [comment]
Conflict. @ChicoXYC , please try to check this with @FLYSTEPHEN and merge after review.

**Comment by hupili** [comment]
Conflict. @ChicoXYC , please try to check this with @FLYSTEPHEN and merge after review.

**Comment by hupili** [comment]
Conflict. @ChicoXYC , please try to check this with @FLYSTEPHEN and merge after review.

**Comment by ChicoXYC** [comment]
ok

**Comment by FLYSTEPHEN** [comment]
We have pushed a new request. The conflict is because my forked repository is not up-to-date when I pushed the request.

**Comment by hupili** [comment]
👍 that is part of the "PR" exercise.

**Pull request closed without merging**
